#add_newline = false             # Don't print a new line at the start of the prompt

# Replace the "â¯" symbol in the prompt with "âŸ¶"
[character]                     # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[directory]                     # The name of the module we are configuring is "directory"
truncation_length = -1
truncate_to_repo = false

[git_branch]                    # The name of the module we are configuring is "git_branch"
symbol = "ğŸ£ "
style = "bold yellow"

[git_status]                    #
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[hostname]                      # The name of the module we are configuring is "hostname"
ssh_only = false
format =  "[$hostname](bold red) "
style = "bold dimmed white"
disabled = false

[memory_usage]                  # The name of the module we are configuring is "memory_usage"
disabled = false
threshold = 30
style = "bold dimmed green"

[package]                       # The name of the module we are configuring is "package"
disabled = true                 # Disable the package module, hiding it from the prompt completely

[time]                          # The name of the module we are configuring is "time"
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"
#utc_time_offset = "-5"
#time_range = "10:00:00-14:00:00"

[username]                      # The name of the module we are configuring is "username"
style_user = "bold dimmed blue"
show_always = true
